### ISSUE TITLE
[Question] About the binary files?

### ISSUE THREAD

**Issue by Suleman-Elahi** [kOFReadie/Multimanager#1]
Would it be possible for you to add builds in the releases?

Thanks

**Comment by ReadieFur** [comment]
Ive not been working on this at all since my last commit, reasons being im rather busy with school right now and im also working a lot on my BSDP-Overlay repo, /Development branch. When I decide to go back to it ill do some stuff but my C# apps were built to be downloaded with the 'repo app' all things there need rewriting anyway.
